/**
 * Audit action enum for tracking system events
 */
export enum AuditAction {
  // System Administrator Management
  SYSTEM_ADMIN_CREATED = 'SYSTEM_ADMIN_CREATED',
  SYSTEM_ADMIN_UPDATED = 'SYSTEM_ADMIN_UPDATED',
  SYSTEM_ADMIN_DELETED = 'SYSTEM_ADMIN_DELETED',
  
  // Permission Management
  PERMISSIONS_ASSIGNED = 'PERMISSIONS_ASSIGNED',
  PERMISSIONS_REVOKED = 'PERMISSIONS_REVOKED',
  
  // System Settings
  SYSTEM_SETTING_UPDATED = 'SYSTEM_SETTING_UPDATED',
  
  // Authentication
  USER_LOGIN = 'USER_LOGIN',
  USER_LOGOUT = 'USER_LOGOUT',
  
  // User Management
  USER_CREATED = 'USER_CREATED',
  USER_UPDATED = 'USER_UPDATED',
  USER_DELETED = 'USER_DELETED',
  
  // Volunteer Club Management
  VOLUNTEER_CLUB_CREATED = 'VOLUNTEER_CLUB_CREATED',
  VOLUNTEER_CLUB_UPDATED = 'VOLUNTEER_CLUB_UPDATED',
  VOLUNTEER_CLUB_DELETED = 'VOLUNTEER_CLUB_DELETED',
}

